### ISSUE TITLE
Improve the UI/UX of KPIs

### ISSUE THREAD

**Issue by luisvasq** [MIT-CAVE/cave_static#49]
#### Tasks
- [x] Add margin between the title and the bookmark icon
- [x] KPI `head`ers should resemble an actual header
- [x] Improve the overall appearance of the KPI components

**Comment by luisvasq** [comment]
Still need to fix a bug where `marquee`able titles stretch the container width too far.
